// GPT_EA standalone MetaTrader 5 entry file
#include "GPT_EA_Part01.mqh"
#include "GPT_EA_Part02.mqh"
#include "GPT_EA_Part03.mqh"
#include "GPT_EA_Part04.mqh"
#include "GPT_EA_Part08_Advanced.mqh"
#include "GPT_EA_Part09_RiskRecoveryAnalytics.mqh"
#include "GPT_EA_Part10_BrokerUniversalRecovery.mqh"
#include "GPT_EA_Part11_PreflightRecoveryGuard.mqh"
#include "GPT_EA_Part12_SafetyStopManagement.mqh"
#include "GPT_EA_Part05.mqh"
#include "GPT_EA_Part06.mqh"
#include "GPT_EA_Part14_StopFailurePolicy.mqh"
#include "GPT_EA_Part13_AdvancedPositionManager.mqh"
#include "GPT_EA_Part07.mqh"
